# Generated by Django 3.1.6 on 2021-02-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210228_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FilePathField(default='blog/background.jpg', path='blog/img'),
        ),
    ]
