# Generated by Django 3.1.6 on 2021-02-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210228_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FilePathField(default='blog/background.jpg', path='img'),
        ),
    ]
