# Generated by Django 3.1.6 on 2021-02-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210228_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FilePathField(default='blog/background.jpg', path='/img'),
        ),
    ]
