# Generated by Django 3.1.6 on 2021-02-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210228_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FilePathField(default='blog/background.jpg', path='/blog/img'),
        ),
    ]
