# Generated by Django 3.1.6 on 2021-02-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210228_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FilePathField(default='blog/img/project1.png', path='/blog/img'),
        ),
    ]
